import Head from "next/head"
import HeroSection from "../components/HeroSection"
import Card from "../components/Card"
import Footer from "../components/Footer"
import { Inter } from "next/font/google"
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] })
const data = [
  {
    title: "Tim Brown",
    description: "A book cover designed for Tim Brown's new release, 'Chage'",
    imgSrc: "/graphic-design/desktop/image-change.jpg",
  },
  {
    title: "Boxed Water",
    description: "A simple packaging concept made for Boxed Water",
    imgSrc: "/graphic-design/desktop/image-boxed-water.jpg",
  },
  {
    title: "Science!",
    description: "A poster made in collaboration with the Federal Art Project",
    imgSrc: "/graphic-design/desktop/image-science.jpg",
  },
]

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-y-10 max-w-2xl lg:max-w-[1110px] px-6 sm:px-10 mx-auto">
        <HeroSection />
        <Card />
      </main>
      <Footer />
    </>
  )
}
