import Head from "next/head"
import { Inter } from "next/font/google"
import Layout from "@/components/layout"
import FeatureSection from "@/components/FeatureSection"
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] })
const data = [
  {
    title: "Airfilter",
    description:
      "Solving the problem of poor indoor air quality by filtering the air",
    imgSrc: "/app-design/desktop/image-airfilter.jpg",
  },
  {
    title: "Eyecam",
    description:
      "Product that lets you edit your favorite photos and videos at any time",
    imgSrc: "/app-design/desktop/image-eyecam.jpg",
  },
  {
    title: "Faceit",
    description:
      "Get to meet your favotie internet superstar with the faceit app",
    imgSrc: "/app-design/desktop/image-faceit.jpg",
  },
  {
    title: "Todo",
    description: "A todo app that features cloud sync with light and dark mode",
    imgSrc: "/app-design/desktop/image-todo.jpg",
  },
  {
    title: "Loopstudios",
    description: "A VR experience app made for Loopstudios",
    imgSrc: "/app-design/desktop/image-loopstudios.jpg",
  },
]

export default function AppDesign() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FeatureSection title="App Design" features={data} />
      </Layout>
    </>
  )
}
