import Head from "next/head"
import FeatureSection from "@/components/FeatureSection"

import Footer from "../components/Footer"
import { Inter } from "next/font/google"
import Navbar from "@/components/Navbar"
import Layout from "@/components/layout"
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ["latin"] })
const data = [
  {
    title: "Express",
    description: "A multi-carrier shippin website for ecommerce business",
    imgSrc: "/web-design/desktop/image-express.jpg",
  },
  {
    title: "Transfer",
    description:
      "Site for low-cost money transfers and sending money within seconds",
    imgSrc: "/web-design/desktop/image-transfer.jpg",
  },
  {
    title: "Photon",
    description:
      "A state-of-the-art music player with high-resolution audio and DSP effects",
    imgSrc: "/web-design/desktop/image-photon.jpg",
  },
  {
    title: "Builder",
    description:
      "Connects users with local contractors based on their location",
    imgSrc: "/web-design/desktop/image-builder.jpg",
  },
  {
    title: "Blogr",
    description:
      "Blogr is a platform for creating an online blog or publication",
    imgSrc: "/web-design/desktop/image-blogr.jpg",
  },
  {
    title: "Camp",
    description:
      "Get expert training in coding, data, design, and digital marketing",
    imgSrc: "/web-design/desktop/image-camp.jpg",
  },
]

export default function WebDesign() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <FeatureSection title="Web Design" features={data} />
      </Layout>
    </>
  )
}
